steps:

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/server-image:$SHORT_SHA", "."]
  id: "docker-build"

- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "dice-service"
    - "--image"
    - "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/server-image"
    - "--max-instances"
    - "1"
    - "--allow-unauthenticated"
    - "--region"
    - "asia-northeast1"
  waitFor: ["docker-build"]

images:
- "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/server-image"

options:
  logging: CLOUD_LOGGING_ONLY