name: deploy-to-gae
on:
  push:
    branches:
      - main
jobs:
  go_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16.0'
      - run: go test ./handlers
